Add barebones account system
pebble-dev/rebble-store pull request #109
Opened 2017-11-07 18:55 UTC by azertyfun

Please read [the backend PR first](https://github.com/pebble-dev/rebblestore-api/pull/28).

This is a frontend implementation for the account system. I have no previous Vue.js experience, so some of the code design choices are probably questionable, and the UI doesn't quite integrate like it should with the current UI, so that will have to be fixed at some point.

2017-11-08 20:24 UTC, Zetaphor commented
@sGerli Will review this tonight

2018-01-28 23:01 UTC, sGerli requested changes

2018-01-28 23:01 UTC, sGerli commented on src/App.vue
> +          client_id: '', // Insert client ID here
Can this be fetched from backend?

2018-01-28 23:01 UTC, sGerli commented on src/components/pages/AccountLogin.vue
> +import VueRecaptcha from 'vue-recaptcha'
You forgot to remove this import

2018-01-28 23:11 UTC, azertyfun commented on src/components/pages/AccountLogin.vue
> +import VueRecaptcha from 'vue-recaptcha'
Well spotted, removing it

2018-01-28 23:11 UTC, azertyfun commented on src/App.vue
> +          client_id: '', // Insert client ID here
Actually yes, on it right now

2018-07-05 14:51 UTC, sGerli commented
No longer relevant

2018-07-05 14:51 UTC, closed without merging