Dragscroll
pebble-dev/rebble-store pull request #121
Opened 2018-02-17 20:36 UTC by MHC03

Issue is #81. This technically works on my test construction with a number of divs and I think it should also work with the real appstore screenshots. But somehow I still got an Internal Server Error when trying to run the backend, so I would like to ask if someone else could test this on my stead.

2018-02-18 01:15 UTC, sGerli commented
![screenshots](https://user-images.githubusercontent.com/3890044/36347194-cd240e6e-1416-11e8-82b3-2bf34aac13b2.PNG)
It is working but something happened to the styles, and they are getting stacked.

2018-02-18 11:09 UTC, MHC03 commented
Shoot, I forgot to float the screenshots. 
I removed some unnecessary div construction from before in above commit and the screenshots should now be floated left, so that they are not stacked.

2018-02-18 22:47 UTC, sGerli requested changes
Everything else seems to be working correctly.

2018-02-18 22:47 UTC, sGerli commented on src/components/pages/widgets/ScreenshotList.vue
> -    -webkit-overflow-scrolling: touch;
I would leave that in there, that's for iOS smooth scrolling.

2018-02-18 22:51 UTC, sGerli commented on src/components/pages/widgets/ScreenshotList.vue
> -    -webkit-overflow-scrolling: touch;
And if possible I also think we should remove the dragscroll-0.0.8.min.js

2018-02-20 00:18 UTC, sGerli commented
You also have to remove it from index.html (line 32)

2018-02-20 11:04 UTC, sGerli approved these changes

2018-02-20 11:04 UTC, merged